### ISSUE TITLE
How to use PBNS_Resizer on non-SMPL human model

### ISSUE THREAD

**Issue by jackieyung** [hbertiche/PBNS#12]
Hi, @hbertiche, I have tried your '[PBNS_Resizer](https://github.com/hbertiche/PBNS/tree/master/PBNS_Resizer)' method, it works well on SMPL human model. I want to try this method on non-SMPL human model, I didn't see related codes. So, would you please release these codes or tell me how to accomplish them?
<img width="648" alt="image" src="https://user-images.githubusercontent.com/13002561/187740511-974644d8-f487-4f05-a1cf-5e77eb9fac9e.png">

**Comment by hbertiche** [comment]
Hi,

thanks for your interest in my work!

PBNS_Resizer adapts the garments to different body shapes and also adjusts garment size (tight/loose),
this is possible with SMPL model because it can change in shape,
to do so, it uses 10 shape parameterts (10-dimensional array) and a set of pre-computed blendshapes (included in SMPL model),
to achieve the same for other non-SMPL models, these models also need to have this characteristic, that is, to contain a set of blendshapes that allows changing the body shape based on a set of shape parameters,
if your human models fulfill this requirement, you can check how to store these models by looking at the structure of `PBNS/PBNS_Resizer/Model/smpl/model_f.mat`
the code might also need a bit of adaptation,

regarding the figure that you show, in that case, that is not PBNS_Resizer, but PBNS,
PBNS animates the garment based on body pose,
PBNS_Resizer "animates" the garment based on body shape and desired looseness/tightness,
potentially, both things could be achieved at the same time with a single model,
